[#24] 목표 리포트, 목표 상세 조회
UMC-5th-Muffler/Money-Planner-BE pull request #33
Opened 2024-01-29 08:32 UTC by heejjinkim

### ✏️ Description

- 목표 리포트 조회 구현
- 목표 리포트 화면 위의 목표 상세 조회 구현

</br>

### 🔑 Key Changes

- 목표 분 리포트 조회 구현
- 목표 상세 조회 구현: 목표 정보와 목표 기간 동안의 총 소비 합

</br>

### 🙏🏻 To Reviewers

- 목표 리포트 조회 시 goal, categoryGoals, dailyPlans, 목표 기간 동안의 expenses가 모두 필요해서 성능이 조금 걱정이 됩니다.. 기존 코드에서 더 성능 최적화 했으면 하는 부분 말씀해주세요.

2024-02-08 07:34 UTC, shortboy7 commented on src/main/java/com/umc5th/muffler/domain/goal/repository/GoalRepository.java
> +    @Query("SELECT g FROM Goal g LEFT JOIN FETCH g.categoryGoals cg LEFT JOIN FETCH cg.category WHERE g.id = :id AND g.member.id = :memberId")
OneToMany로 연관된 엔티티는 fetch join시 distinct를 붙여야 한다고 하네여.

기왕 가져오는거 DailyPlan까지 같이 가져오면 안되나여?! 

https://studyandwrite.tistory.com/477

2024-02-08 07:36 UTC, shortboy7 commented on src/main/java/com/umc5th/muffler/domain/goal/dto/GoalConverter.java
> +        for (DailyPlan dailyPlan : dailyPlans) {
ORM의 장점과 DailyPlan과의 OneToMany 맵핑한 것을 살려서 Goal 엔티티 내부에 
 
 public long getTotalCost(), public long getTotalZeroDay() 같은 메서드를 구현해 써보는건 어떨까요?

2024-02-08 07:41 UTC, shortboy7 commented on src/main/java/com/umc5th/muffler/domain/goal/dto/GoalConverter.java
> +        String mostUsedCategory = sortedCategoryReports.isEmpty() ? null : sortedCategoryReports.get(0).getCategoryName();
카테고리 골에 등록되지 않은 카테고리가 가장 많은 금액을 소비할 경우 문제가 될 것 같습니다.

categoryGoal 가 {id : 1, budget: 10} 만 등록되어 있고,
expense에 {id : 2, cost: 1000} 일 경우, 가장 많이 소비된 것은 id가 2인 카테고리 이름으로 나와야 하지 않을까여?!

제가 기획을 자세하게 파악 못해서 그런 것일 수도 있으니 참고해주세요

2024-02-08 07:51 UTC, shortboy7 commented on src/main/java/com/umc5th/muffler/domain/goal/dto/CategoryGoalReportDto.java
> +    private Long totalCost;
Builder를 쓰는 이상 Builder.Default로 totalCost, avgCost는 0으로 초기화 하는게 안전해보여용

2024-02-08 08:00 UTC, heejjinkim commented on src/main/java/com/umc5th/muffler/domain/goal/repository/GoalRepository.java
> +    @Query("SELECT g FROM Goal g LEFT JOIN FETCH g.categoryGoals cg LEFT JOIN FETCH cg.category WHERE g.id = :id AND g.member.id = :memberId")
넵 distinct 붙이도록 하겠습니다!
2개 이상의 OneToMany를 조인하면 MultipleBagFetchException 오류가 발생합니다ㅜ 모두 다 한번에 가져오려면 Goal 엔티티 안의 CategoryGoals와 DailyPlans를 Set 타입으로 선언해야 하는데 이러면 다른 부분 코드도 모두 바꿔야 해서 DailyPlans를 조회하는 쿼리가 한 번 더 발생하는 것은 어쩔 수 없을 것 같습니다..

2024-02-08 08:00 UTC, heejjinkim commented on src/main/java/com/umc5th/muffler/domain/goal/dto/GoalConverter.java
> +        String mostUsedCategory = sortedCategoryReports.isEmpty() ? null : sortedCategoryReports.get(0).getCategoryName();
아하 맞는 말씀입니다. 수정하도록 하겠습니다.

2024-02-08 08:00 UTC, shortboy7 commented on src/main/java/com/umc5th/muffler/domain/goal/dto/GoalConverter.java
> +        Map<Long, CategoryGoalReportDto> categoryReportsMap = initCtegoryReportsMap(categoryGoals);
오타있슴다.

2024-02-08 08:03 UTC, jwsong98 requested changes
이 정도만 수정하면 될 것 같아요

2024-02-12 12:44 UTC, heejjinkim commented on src/main/java/com/umc5th/muffler/domain/goal/dto/GoalConverter.java
> +        for (DailyPlan dailyPlan : dailyPlans) {
Goal 엔티티에 두 함수를 추가하게 되면 dailyPlans를 두 번 순회하면서 계산해야 해서 지금처럼 한 번만 순회해서 둘을 한꺼번에 계산하는 게 성능 상 괜찮을 것 같습니다..!

2024-02-12 17:47 UTC, heejjinkim commented
수정 완료 했습니다!

2024-02-15 06:15 UTC, shortboy7 approved these changes

2024-02-15 06:16 UTC, merged